### ISSUE TITLE
No super method getLifecycle()Landroidx/lifecycle/Lifecycle; 

### ISSUE THREAD

**Issue by LisonLiou** [o0o0oo00/Pudding#3]
`2019-07-09 15:49:45.095 30778-30778/cc.lison.pocketwarehouse E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cc.lison.pocketwarehouse, PID: 30778
    java.lang.NoSuchMethodError: No super method getLifecycle()Landroidx/lifecycle/Lifecycle; in class Landroidx/core/app/ComponentActivity; or its super classes (declaration of 'androidx.core.app.ComponentActivity' appears in /data/app/cc.lison.pocketwarehouse-1/base.apk)
        at androidx.fragment.app.FragmentActivity.getLifecycle(FragmentActivity.java:324)
        at com.zcy.pudding.Pudding.setActivity(Pudding.kt:91)
        at com.zcy.pudding.Pudding.access$setActivity(Pudding.kt:23)
        at com.zcy.pudding.Pudding$Companion.create(Pudding.kt:112)
        at cc.lison.pocketwarehouse.util.kt.PuddingUtil$Companion.pudd(PuddingUtil.kt:17)
        at cc.lison.pocketwarehouse.ui.activity.ExWarehouseActivity.onFailed(ExWarehouseActivity.java:124)
        at cc.lison.pocketwarehouse.presenter.ExWarehousePresenter$2.onFailed(ExWarehousePresenter.java:125)
        at duozhao.com.baselib.net.io.NetProcess$3.run(NetProcess.java:66)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by LisonLiou** [comment]
你好，集成进安卓项目，运行时错误；封装了一个fun，调用时候报错，Activity类型也是AppCompactActivity
`import androidx.appcompat.app.AppCompatActivity;
import com.zcy.pudding.Pudding

/**
 * Created by Lison on 7/9/2019.
 *
 * http://lison.cc
 */


class PuddingUtil {

    companion object {
        fun pudd(activity: AppCompatActivity, title: String, text: String) {
            Pudding.create(activity) {
                setTitle(title)
                setText(text)
            }.show()
        }
    }
}`

**Comment by o0o0oo00** [comment]
> 你好，集成进安卓项目，运行时错误；封装了一个fun，调用时候报错，Activity类型也是AppCompactActivity
> `import androidx.appcompat.app.AppCompatActivity;
> import com.zcy.pudding.Pudding
> 
> /**
> 
> * Created by Lison on 7/9/2019.
> * http://lison.cc
>   */
> 
> class PuddingUtil {
> 
> ```
> companion object {
>     fun pudd(activity: AppCompatActivity, title: String, text: String) {
>         Pudding.create(activity) {
>             setTitle(title)
>             setText(text)
>         }.show()
>     }
> }
> ```
> 
> }`

> 你好，集成进安卓项目，运行时错误；封装了一个fun，调用时候报错，Activity类型也是AppCompactActivity
> `import androidx.appcompat.app.AppCompatActivity;
> import com.zcy.pudding.Pudding
> 
> /**
> 
> * Created by Lison on 7/9/2019.
> * http://lison.cc
>   */
> 
> class PuddingUtil {
> 
> ```
> companion object {
>     fun pudd(activity: AppCompatActivity, title: String, text: String) {
>         Pudding.create(activity) {
>             setTitle(title)
>             setText(text)
>         }.show()
>     }
> }
> ```
> 
> }`

这个应该是你的`androidx.appcompat:appcompat`版本不对，试试升级的到最新版

另外o(*￣3￣)o
你是觉得我封装的不好嘛？你还要再在伴生对象里面封装一次。委屈巴巴~~
